title: AI Conference Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: sxl

domain: "sxldj.github.io"
baseurl: ""

twitter_username: none
twitter_hashtag: none
github_username: sxldj
github_repo: sxldj.github.io

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']